### ISSUE TITLE
align_image_stack fails under flatpack version

### ISSUE THREAD

**Issue by acobaugh** [LuminanceHDR/LuminanceHDR#140] opened 2018-11-22 16:15 UTC
align_image_stack fails to run under the flatpack version of LuminanceHDR. Hugin is installed, and align_image_stack is available in my PATH. Unsure if this is a problem with flatpack, how I'm running it, or the flatpack of luminance itself.

Running under voidlinux. Version info:
```[11:12:21] acobaugh@zirzla ~
% uname -a
Linux zirzla 4.18.16_2 #1 SMP PREEMPT Mon Oct 29 16:10:00 UTC 2018 x86_64 GNU/Linux
[11:12:23] acobaugh@zirzla ~
% flatpak info net.sourceforge.qtpfsgui.LuminanceHDR
Ref: app/net.sourceforge.qtpfsgui.LuminanceHDR/x86_64/stable
ID: net.sourceforge.qtpfsgui.LuminanceHDR
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-11-19 19:37:32 +0000
Subject: fix typo in appstream description. (9e708de4)
Commit: 04c80f00af178af11c57b2eecc075bc18bd84e117d85793cccf3799578b73678
Parent: d09dc7de138f0c349911b0414e14370106eba0c594965f950c9aa19254f98caf
Location: /var/lib/flatpak/app/net.sourceforge.qtpfsgui.LuminanceHDR/x86_64/stable/04c80f00af178af11c57b2eecc075bc18bd84e117d85793cccf3799578b73678
Installed size: 27.4 MB
Runtime: org.kde.Platform/x86_64/5.11
Sdk: org.kde.Sdk/x86_64/5.11
```

Command line:
```flatpak run --filesystem=host -v net.sourceforge.qtpfsgui.LuminanceHDR ./20181121-153605*.NEF```

Verbose output:
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/acobaugh/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/acobaugh/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/acobaugh/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 482844814
F: Allocated instance id 1134757763
F: Document portal not available, not mounting /run/user/1000/doc
F: Allowing dri access
F: Allowing host-fs access
F: Allowing homedir access
F: Allowing x11 access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running 'bwrap --args 29 /usr/libexec/flatpak-dbus-proxy --args=31'
F: Running 'bwrap --args 26 luminance-hdr ./20181121-153605.NEF ./20181121-153605_1.NEF ./20181121-153605_2.NEF'
libpng warning: iCCP: known incorrect sRGB profile
void HdrWizard::resizeEvent(QResizeEvent*)
"HdrCreationManager::loadFiles(): Checking ./20181121-153605.NEF"
"HdrCreationManager::loadFiles(): Schedule loading for ./20181121-153605.NEF"
"HdrCreationManager::loadFiles(): Checking ./20181121-153605_1.NEF"
"HdrCreationManager::loadFiles(): Schedule loading for ./20181121-153605_1.NEF"
"HdrCreationManager::loadFiles(): Checking ./20181121-153605_2.NEF"
"HdrCreationManager::loadFiles(): Schedule loading for ./20181121-153605_2.NEF"
"LoadFile: Loading data for ./20181121-153605_1.NEF"
"LoadFile: Loading data for ./20181121-153605.NEF"
"LoadFile: Loading data for ./20181121-153605_2.NEF"
"LoadFile: Average Luminance for ./20181121-153605.NEF is 0.00256233"
"LoadFile: Average Luminance for ./20181121-153605_1.NEF is 0.000655454"
"LoadFile: Average Luminance for ./20181121-153605_2.NEF is 0.00998464"
HdrCreationManager::loadFilesDone(): Data loaded ... move to internal structure!
"HdrCreationManager::loadFilesDone(): Insert data for ./20181121-153605.NEF"
"HdrCreationManager::loadFilesDone(): Insert data for ./20181121-153605_1.NEF"
"HdrCreationManager::loadFilesDone(): Insert data for ./20181121-153605_2.NEF"
"HdrCreationManager::refreshEVOffset(): offset = -8.60833"
HdrWizard::loadInputFilesDone()
HdrWizard::updateTableGrid(): Fill grid with values in the m_data structure
"HdrWizard::updateTableGrid(): Fill row 0: ./20181121-153605.NEF -8.60833 EV (0 EV)"
"HdrWizard::updateTableGrid(): Fill row 1: ./20181121-153605_1.NEF -10.5752 EV (-1.96689 EV)"
"HdrWizard::updateTableGrid(): Fill row 2: ./20181121-153605_2.NEF -6.64607 EV (1.96225 EV)"
"HdrWizard::inputHdrFileSelected(0)"
"SaveFile: Saving data for ./20181121-153605_1.NEF to /tmp/{db4d60c2-0219-4ce7-85be-8e305338293e}.tif on /tmp"
"SaveFile: Saving data for ./20181121-153605.NEF to /tmp/{63ef33e4-3d04-4750-8f0d-2f498857d0ac}.tif on /tmp"
"SaveFile: Saving data for ./20181121-153605_2.NEF to /tmp/{b5b279fb-bd20-4b0e-be5b-d374ea4e2fc1}.tif on /tmp"
ais_parameters  ("-v", "-a", "{f33613a6-775f-48b6-b6d1-d595a413e2cb}", "{63ef33e4-3d04-4750-8f0d-2f498857d0ac}.tif", "{db4d60c2-0219-4ce7-85be-8e305338293e}.tif", "{b5b279fb-bd20-4b0e-be5b-d374ea4e2fc1}.tif")
ais started
align_image_stack failed
void HdrCreationManager::ais_finished: remove  "/tmp/{63ef33e4-3d04-4750-8f0d-2f498857d0ac}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0000.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{db4d60c2-0219-4ce7-85be-8e305338293e}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0001.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{b5b279fb-bd20-4b0e-be5b-d374ea4e2fc1}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0002.tif"
align_image_stack failed
void HdrCreationManager::ais_finished: remove  "/tmp/{63ef33e4-3d04-4750-8f0d-2f498857d0ac}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0000.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{db4d60c2-0219-4ce7-85be-8e305338293e}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0001.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{b5b279fb-bd20-4b0e-be5b-d374ea4e2fc1}.tif"
void HdrCreationManager::ais_finished: remove  "/tmp/{f33613a6-775f-48b6-b6d1-d595a413e2cb}0002.tif"
```

**Comment by fcomida** [comment] 2018-11-22 21:17
Unfortunately Hugin hasn't been packaged as flatpak, I tried copying the host version to the flatpak filesystem and it fails because it's linked to a (or more) version of some library different from the ones provided by flatpak runtime. I asked @anxolerd whether he can find the time for pagckaging Hugin as well.

**Comment by anxolerd** [comment] 2018-11-23 01:38
This is definitely a flatpak distribution issue.

The problem is that 
1) flatpak does not allow you to pass /usr/bin easily into container, even with `--filesystem=host`
2) As far as I understood LuminanceHDR code, it checks for directory, where LuminanceHDR binary is located.

Trying to build `align_image_stack` into the LHDR distribution, but this one is tricky one.

**Comment by fcomida** [comment] 2018-11-24 02:29
Fixed by adding align_image_stack to the distribution.

**Closed by fcomida** 2018-11-24 02:29 UTC
